"""add required field to pregunta

Revision ID: ccbc640c1ce3
Revises: c8a669ba6174
Create Date: 2025-10-07 20:16:14.924743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbc640c1ce3'
down_revision = 'c8a669ba6174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formularios', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preguntas', schema=None) as batch_op:
        batch_op.drop_column('required')

    with op.batch_alter_table('formularios', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
