"""add required field to preguntas

Revision ID: ddc176aa5906
Revises: ccbc640c1ce3
Create Date: 2025-10-07 20:44:21.164870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc176aa5906'
down_revision = 'ccbc640c1ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.alter_column('pregunta_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('respuesta', schema=None) as batch_op:
        batch_op.alter_column('pregunta_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
